apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yrei
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-yrei@sha256:ded5a82f1c55cf250b92aa5357b7f79db2164dc3e480e7e6bc25de55a70e3b93
        name: my-nodejs
        resources: {}
status: {}
